# ==================== BUILD STAGE ====================
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Удаляем devDependencies после сборки
RUN npm prune --production

# ==================== PRODUCTION STAGE ====================
FROM node:22-alpine AS production

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/resources ./resources

ENV PORT=3000
ENV NO_COLOR=true
ENV TZ=UTC

EXPOSE $PORT

CMD [ "sh", "-c", "yarn start:prod" ]