export enum ExceptionCode {
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
